import React from 'react'
import Login from "../components/Login";
import { HMSRoomProvider } from "@100mslive/react-sdk";
import Head from 'next/head'
function video() {
  return (
    <HMSRoomProvider>
    <div>
      <Head>
        <title>Videome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
    </HMSRoomProvider>
  )
}

export default video
